# PLAY level variables
- name: variables from PLAY level
  hosts: localhost
  vars:
    Course: "DevOps with AWS"
    Trainer: "Ramesh"
    Duration: "120HRS"
  tasks:
    - name: check variables
      ansible.builtin.debug:
        msg: "Hi, I am learning {{Course}}, Trainer is {{Trainer}}, Duration is {{Duration}}"