- name: loops
  hosts: localhost
  become: yes
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name: "{{item}}"
        state: present # item is a default keyword
      loop:
        - git
        - mysql
        - postfix
